


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."ms_get_portal_payload"("p_email" "text" DEFAULT 'demo@marketstate.ai'::"text") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
declare
  v_user_id uuid;
  v_payload jsonb;
begin
  select id
  into v_user_id
  from public.ms_profiles
  where email = p_email;

  if v_user_id is null then
    raise exception 'No profile found for %', p_email;
  end if;

  select jsonb_build_object(
    'profile', (
      select row_to_json(p)
      from (
        select id, email, display_name, risk_profile, created_at
        from public.ms_profiles
        where id = v_user_id
      ) p
    ),
    'snapshot', (
      select row_to_json(s)
      from (
        select as_of_date, total_value, cash_balance, day_pnl, total_return_pct
        from public.ms_portfolio_snapshots
        where user_id = v_user_id
        order by as_of_date desc
        limit 1
      ) s
    ),
    'holdings', (
      select coalesce(jsonb_agg(h order by h.symbol), '[]'::jsonb)
      from (
        select symbol, company_name, quantity, price, change_pct
        from public.ms_holdings
        where user_id = v_user_id
      ) h
    ),
    'watchlist', (
      select coalesce(jsonb_agg(w order by w.symbol), '[]'::jsonb)
      from (
        select symbol, price, change_pct
        from public.ms_watchlist
        where user_id = v_user_id
      ) w
    ),
    'activity', (
      select coalesce(jsonb_agg(a order by a.activity_time desc), '[]'::jsonb)
      from (
        select activity_text, activity_time
        from public.ms_activity_log
        where user_id = v_user_id
        order by activity_time desc
        limit 10
      ) a
    )
  )
  into v_payload;

  return v_payload;
end;
$$;


ALTER FUNCTION "public"."ms_get_portal_payload"("p_email" "text") OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Test Table" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."Test Table" OWNER TO "postgres";


ALTER TABLE "public"."Test Table" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Test Table_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ms_activity_log" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "activity_text" "text" NOT NULL,
    "activity_time" timestamp with time zone NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."ms_activity_log" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."ms_activity_log_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."ms_activity_log_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."ms_activity_log_id_seq" OWNED BY "public"."ms_activity_log"."id";



CREATE TABLE IF NOT EXISTS "public"."ms_holdings" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "symbol" "text" NOT NULL,
    "company_name" "text" NOT NULL,
    "quantity" numeric(18,4) NOT NULL,
    "price" numeric(14,2) NOT NULL,
    "change_pct" numeric(7,3) NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "ms_holdings_price_check" CHECK (("price" >= (0)::numeric)),
    CONSTRAINT "ms_holdings_quantity_check" CHECK (("quantity" >= (0)::numeric))
);


ALTER TABLE "public"."ms_holdings" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."ms_holdings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."ms_holdings_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."ms_holdings_id_seq" OWNED BY "public"."ms_holdings"."id";



CREATE TABLE IF NOT EXISTS "public"."ms_portfolio_snapshots" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "as_of_date" "date" DEFAULT CURRENT_DATE NOT NULL,
    "total_value" numeric(14,2) NOT NULL,
    "cash_balance" numeric(14,2) NOT NULL,
    "day_pnl" numeric(14,2) NOT NULL,
    "total_return_pct" numeric(7,3) NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."ms_portfolio_snapshots" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."ms_portfolio_snapshots_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."ms_portfolio_snapshots_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."ms_portfolio_snapshots_id_seq" OWNED BY "public"."ms_portfolio_snapshots"."id";



CREATE TABLE IF NOT EXISTS "public"."ms_profiles" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "auth_user_id" "uuid",
    "email" "text" NOT NULL,
    "display_name" "text" NOT NULL,
    "risk_profile" "text" DEFAULT 'balanced'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."ms_profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."ms_watchlist" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "symbol" "text" NOT NULL,
    "price" numeric(14,2) NOT NULL,
    "change_pct" numeric(7,3) NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "ms_watchlist_price_check" CHECK (("price" >= (0)::numeric))
);


ALTER TABLE "public"."ms_watchlist" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."ms_watchlist_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."ms_watchlist_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."ms_watchlist_id_seq" OWNED BY "public"."ms_watchlist"."id";



ALTER TABLE ONLY "public"."ms_activity_log" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."ms_activity_log_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."ms_holdings" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."ms_holdings_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."ms_portfolio_snapshots" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."ms_portfolio_snapshots_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."ms_watchlist" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."ms_watchlist_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."Test Table"
    ADD CONSTRAINT "Test Table_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ms_activity_log"
    ADD CONSTRAINT "ms_activity_log_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ms_activity_log"
    ADD CONSTRAINT "ms_activity_log_user_id_activity_text_activity_time_key" UNIQUE ("user_id", "activity_text", "activity_time");



ALTER TABLE ONLY "public"."ms_holdings"
    ADD CONSTRAINT "ms_holdings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ms_holdings"
    ADD CONSTRAINT "ms_holdings_user_id_symbol_key" UNIQUE ("user_id", "symbol");



ALTER TABLE ONLY "public"."ms_portfolio_snapshots"
    ADD CONSTRAINT "ms_portfolio_snapshots_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ms_portfolio_snapshots"
    ADD CONSTRAINT "ms_portfolio_snapshots_user_id_as_of_date_key" UNIQUE ("user_id", "as_of_date");



ALTER TABLE ONLY "public"."ms_profiles"
    ADD CONSTRAINT "ms_profiles_auth_user_id_key" UNIQUE ("auth_user_id");



ALTER TABLE ONLY "public"."ms_profiles"
    ADD CONSTRAINT "ms_profiles_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."ms_profiles"
    ADD CONSTRAINT "ms_profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ms_watchlist"
    ADD CONSTRAINT "ms_watchlist_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ms_watchlist"
    ADD CONSTRAINT "ms_watchlist_user_id_symbol_key" UNIQUE ("user_id", "symbol");



CREATE INDEX "idx_ms_activity_user_time" ON "public"."ms_activity_log" USING "btree" ("user_id", "activity_time" DESC);



CREATE INDEX "idx_ms_holdings_user" ON "public"."ms_holdings" USING "btree" ("user_id");



CREATE INDEX "idx_ms_snapshots_user_date" ON "public"."ms_portfolio_snapshots" USING "btree" ("user_id", "as_of_date" DESC);



CREATE INDEX "idx_ms_watchlist_user" ON "public"."ms_watchlist" USING "btree" ("user_id");



ALTER TABLE ONLY "public"."ms_activity_log"
    ADD CONSTRAINT "ms_activity_log_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."ms_profiles"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."ms_holdings"
    ADD CONSTRAINT "ms_holdings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."ms_profiles"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."ms_portfolio_snapshots"
    ADD CONSTRAINT "ms_portfolio_snapshots_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."ms_profiles"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."ms_profiles"
    ADD CONSTRAINT "ms_profiles_auth_user_id_fkey" FOREIGN KEY ("auth_user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."ms_watchlist"
    ADD CONSTRAINT "ms_watchlist_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."ms_profiles"("id") ON DELETE CASCADE;



ALTER TABLE "public"."Test Table" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ms_activity_log" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "ms_activity_public_read_demo" ON "public"."ms_activity_log" FOR SELECT USING (true);



ALTER TABLE "public"."ms_holdings" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "ms_holdings_public_read_demo" ON "public"."ms_holdings" FOR SELECT USING (true);



CREATE POLICY "ms_portfolio_public_read_demo" ON "public"."ms_portfolio_snapshots" FOR SELECT USING (true);



ALTER TABLE "public"."ms_portfolio_snapshots" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ms_profiles" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "ms_profiles_public_read_demo" ON "public"."ms_profiles" FOR SELECT USING (true);



ALTER TABLE "public"."ms_watchlist" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "ms_watchlist_public_insert_demo" ON "public"."ms_watchlist" FOR INSERT TO "authenticated", "anon" WITH CHECK (true);



CREATE POLICY "ms_watchlist_public_read_demo" ON "public"."ms_watchlist" FOR SELECT USING (true);



CREATE POLICY "ms_watchlist_public_update_demo" ON "public"."ms_watchlist" FOR UPDATE TO "authenticated", "anon" USING (true) WITH CHECK (true);





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."ms_get_portal_payload"("p_email" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."ms_get_portal_payload"("p_email" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."ms_get_portal_payload"("p_email" "text") TO "service_role";


















GRANT ALL ON TABLE "public"."Test Table" TO "anon";
GRANT ALL ON TABLE "public"."Test Table" TO "authenticated";
GRANT ALL ON TABLE "public"."Test Table" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Test Table_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Test Table_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Test Table_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."ms_activity_log" TO "anon";
GRANT ALL ON TABLE "public"."ms_activity_log" TO "authenticated";
GRANT ALL ON TABLE "public"."ms_activity_log" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ms_activity_log_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ms_activity_log_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ms_activity_log_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."ms_holdings" TO "anon";
GRANT ALL ON TABLE "public"."ms_holdings" TO "authenticated";
GRANT ALL ON TABLE "public"."ms_holdings" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ms_holdings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ms_holdings_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ms_holdings_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."ms_portfolio_snapshots" TO "anon";
GRANT ALL ON TABLE "public"."ms_portfolio_snapshots" TO "authenticated";
GRANT ALL ON TABLE "public"."ms_portfolio_snapshots" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ms_portfolio_snapshots_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ms_portfolio_snapshots_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ms_portfolio_snapshots_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."ms_profiles" TO "anon";
GRANT ALL ON TABLE "public"."ms_profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."ms_profiles" TO "service_role";



GRANT ALL ON TABLE "public"."ms_watchlist" TO "anon";
GRANT ALL ON TABLE "public"."ms_watchlist" TO "authenticated";
GRANT ALL ON TABLE "public"."ms_watchlist" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ms_watchlist_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ms_watchlist_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ms_watchlist_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";

drop policy "ms_watchlist_public_insert_demo" on "public"."ms_watchlist";

drop policy "ms_watchlist_public_update_demo" on "public"."ms_watchlist";


  create policy "ms_watchlist_public_insert_demo"
  on "public"."ms_watchlist"
  as permissive
  for insert
  to anon, authenticated
with check (true);



  create policy "ms_watchlist_public_update_demo"
  on "public"."ms_watchlist"
  as permissive
  for update
  to anon, authenticated
using (true)
with check (true);



